### ISSUE TITLE
Schema validation errors -> TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by Jean-MichelBenoit** [sirosen/check-jsonschema#1]
Hook detail:
```
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.3.0
  hooks:
    - id: check-jsonschema
      language: python
      files: \.(json)$
      args: ["--schemafile", "./schemas/myschemafile.json"]
```

In check_jsonschema.py, if a schema validations was encountered, when building the json path, the join() fonction throws an unexpected error around line 125.

```
Schema validation errors were encountered.
Traceback (most recent call last):
  File "/Users/myuser/.cache/pre-commit/repo_qktbzsh/py_env-python3.9/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/myuser/.cache/pre-commit/repo_qktbzsh/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema.py", line 127, in main
    ".".join(x if "." not in x else f'"{x}"' for x in err.path)
  File "/Users/myuser/.cache/pre-commit/repo_qktbzsh/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema.py", line 127, in <genexpr>
    ".".join(x if "." not in x else f'"{x}"' for x in err.path)
TypeError: argument of type 'int' is not iterable
```

When printing err.path, it shows as a dequeue entry, the first element is the json element key name, and the second entry seems to be its depth in the file. The second entry is an int, which seems to be the root cause of the unexpected exception.

**Potential fix:**
By stringifying 'x' in the join() function, the error dissapears and log outputs shows what seems to be a more intelligible error message for end users:

```
Schema validation errors were encountered.
  myfile.json::jsonelement-name.9.myattribute: 'valueXYZ' is not one of ['A', 'B', 'C', 'D']
```

**Comment by sirosen** [comment]
#2 is merged and I've just tagged `main` as `0.3.1`.

So you can now get the fixed version by updating pre-commit to use v0.3.1
