### ISSUE TITLE
Validation of Azure pipeline gives strange error

### ISSUE THREAD

**Issue by Borda** [sirosen/check-jsonschema#10]
running the same checking as #411 and getting the following error?
```
 'PublishCodeCoverageResults@2' is not one of ['PowerShell@2']
```
docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results
the cmd used was 
```bash
check-jsonschema .azure-pipelines/*.yml --schemafile "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.188.1/service-schema.json"
```

transfering from https://github.com/microsoft/azure-pipelines-vscode/issues/412

**Comment by sirosen** [comment]
The update to the latest azure pipelines schema has been released as v0.4.1

Let me know if you see any issues with the update, but this should be resolved. Thanks again for the fix! You've been credited in the changelog. 😄
