### ISSUE TITLE
Add or link to docs on how to write schema

### ISSUE THREAD

**Issue by janosh** [sirosen/check-jsonschema#14]
Cool project! I'm quite new to schemas though. Perhaps the readme could be expanded with some instructions on how to write your own schema. If that's too involved, maybe link to another source?

**Comment by sirosen** [comment]
JSON Schema is a fairly complex spec; well beyond the scope of this project to document.
But I can definitely add links to the spec in the readme; I'll put that on my todo list.

For right now:

Here's a link to the spec: https://json-schema.org/
And here's the github page for the python implementation used in check-jsonschema: https://github.com/Julian/jsonschema/

I think those are the only appropriate links to add.

**Comment by sirosen** [comment]
You probably want the `pattern` keyword: https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.3.3

Most of the examples on the json-schema site are too simple to use `pattern` or `patternProperties`, but this one does: https://json-schema.org/learn/file-system.html

I'm far from an expert on jsonschema. If you have questions, you might be better served asking the folks who maintain the spec. e.g. https://json-schema.org/slack

**Comment by janosh** [comment]
I started with a very simple schema:

```json
{
  "id": {
    "type": "integer"
  },
  "title": {
    "type": "string"
  }
}
```

The output I'm getting from `check-jsonschema` is:

```sh
$ pre-commit run check-jsonschema -av
Validate files with jsonschema...........................................Failed
- hook id: check-jsonschema
- duration: 0.22s
- exit code: 1

Traceback (most recent call last):
  File "/Users/janosh/.cache/pre-commit/repom4g5zgiq/py_env-python3.9/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/janosh/.cache/pre-commit/repom4g5zgiq/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/__init__.py", line 13, in main
    validator = schema_loader.get_validator()
  File "/Users/janosh/.cache/pre-commit/repom4g5zgiq/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/loaders.py", line 42, in get_validator
    validator_cls.check_schema(schema)
  File "/Users/janosh/.cache/pre-commit/repom4g5zgiq/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 294, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: {'type': 'string'} is not of type 'string'

Failed validating 'type' in metaschema['properties']['title']:
    {'type': 'string'}

On schema['title']:
    {'type': 'string'}
```

I can't figure out what document contains `title` keys that aren't strings.
