### ISSUE TITLE
update jsonschema version

### ISSUE THREAD

**Issue by foolioo** [sirosen/check-jsonschema#26]
At the time of writing, [jsonschema latest release is 4.2.1](https://github.com/Julian/jsonschema/releases/).
Any reason why not to update to the latest version? If that is ok, I can open a pull request.

https://github.com/sirosen/check-jsonschema/blob/3662354a762060f5bcf155a7d962fe87c04cab31/setup.cfg#L21

**Comment by sirosen** [comment]
I would happily accept a PR updating to `jsonschema<5.0`. I could also probably get to it in the next few days.
I just looked at the 4.0 changelog and there don't seem to be any problematic removals.

4.0 added a new property to `ValidationError` objects, `json_path`. It might be worth updating to require `jsonschema>=4.0,<5.0` and use that for error display. I'll think about that a little.
