### ISSUE TITLE
execution fails

### ISSUE THREAD

**Issue by foolioo** [sirosen/check-jsonschema#3]
reproduce:

```shell
$ python3 -m venv venv
$ source venv/bin/activate
$ python --version
Python 3.9.5

$ pip install check-jsonschema -q
$ check-jsonschema --help
Traceback (most recent call last):
  File "/home/foo/tmp/venv/bin/check-jsonschema", line 5, in <module>
    from check_jsonschema import main
ImportError: cannot import name 'main' from 'check_jsonschema' (/home/foo/tmp/venv/lib/python3.9/site-packages/check_jsonschema/__init__.py)
```

is it a bug?

seems like it can be fixed by patching `venv/bin/check-jsonschema`

```shell
$ diff venv/bin/check-jsonschema venv/bin/check-jsonschema.orig
5c5
< from check_jsonschema.cli import main
---
> from check_jsonschema import main

$ check-jsonschema --help
usage: check-jsonschema [-h] --schemafile SCHEMAFILE [--cache-filename CACHE_FILENAME] instancefiles [instancefiles ...]

positional arguments:
  instancefiles         JSON or YAML files to check.

optional arguments:
  -h, --help            show this help message and exit
  --schemafile SCHEMAFILE
                        REQUIRED. The path to a file containing the jsonschema to use or an HTTP(S) URI for the schema. If a remote
                        file is used, it will be downloaded and cached locally based on mtime.
  --cache-filename CACHE_FILENAME
                        The name to use for caching a remote schema. Defaults to the last slash-delimited part of the URI.
```

**Comment by sirosen** [comment]
Are you certain that the reproduction is accurate? This looks to me like a bad upgrade from an older version, before the switch from a package layout to a single module layout.

When I do a pip install into a virtualenv generated by `python3.9 -m venv`, I get the correctly generated shim with `from check_jsonschema import main`.

If it does persist, can you share what you see in `venv/lib/python3.9/site-packages/check_jsonschema-*.dist-info/`?
Specifically, I'd like to know if there's a file there named `WHEEL`.

**Comment by sirosen** [comment]
A somewhat related note: thanks for submitting #5 ! I've just released it as v0.3.2 .

Please check if you still see this issue on that version. I took a little extra care to ensure the package build was done with a clean repo, in case there was an issue.

**Comment by foolioo** [comment]
> I took a little extra care to ensure the package build was done with a clean repo, in case there was an issue.

now `check-jsonschema --help` works flawlessly with version 0.3.2.

i think there is another issue...
having 10 files that are checked using the pre-commit hook, on a fresh run (cache directory does not exist) the check fails (but the cache is populated with the schemas) but when running pre-commit again, everything passes ok.

i am trying to understand what is the `cached_open()` and whether this is where the issue raises.

https://github.com/sirosen/check-jsonschema/blob/55459500380710e3b2043256617a6bd0e8db6b18/check_jsonschema.py#L96

**Comment by foolioo** [comment]
@sirosen:

> I took a little extra care to ensure the package build was done with a clean repo, in case there was an issue.

now `check-jsonschema --help` works flawlessly with version 0.3.2.

i think there is another issue...
having 10 files that are checked using the pre-commit hook, on a fresh run (cache directory does not exist) the check fails (but the cache is populated with the schemas) but when running pre-commit again, everything passes ok.

i am trying to understand what is the `cached_open()` and whether this is where the issue raises.

https://github.com/sirosen/check-jsonschema/blob/55459500380710e3b2043256617a6bd0e8db6b18/check_jsonschema.py#L96

**Comment by foolioo** [comment]
issue is gone, closing this.
