### ISSUE TITLE
Fix reusableWorkflowCallJob to allow uses property to have a local path

### ISSUE THREAD

**Issue by pdietl** [sirosen/check-jsonschema#30]
Currently, `reusableWorkflowCallJob` only allows for `'{owner}/{repo}/{path}/{filename}@{ref}'`, but the following is also allowed: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses `./{path}/{filename}`

**Comment by sirosen** [comment]
I'll try to make some time soon to look at updating the schemastore schema. This needs to be fixed upstream, and then check-jsonschema can pick up on the change.

**Comment by sirosen** [comment]
This was fixed in the schemastore schema. I'll have to do a release at some point for the vendored copy, but for most usages this should be resolved.

Let me know if there's an issue (or if you need the release done sooner). And thanks for reporting!

**Comment by pdietl** [comment]
I encountered this issue and had to disable this check in pre-commit. Having a new release with this fix would be amazing

**Comment by sirosen** [comment]
I've done a release (v0.10.1). I wasn't originally sure I'd get to it today.
Let me know if that doesn't work for you.

**Comment by pdietl** [comment]
It fixed it! Thank you <3
