### ISSUE TITLE
Parallel runs are unsafe until cache is populated

### ISSUE THREAD

**Issue by sirosen** [sirosen/check-jsonschema#8]
#7 is the originator of this.

> @sirosen: solved by using [`require_serial: true`](https://pre-commit.com/#hooks-require_serial)

_Originally posted by @foolioo in https://github.com/sirosen/check-jsonschema/issues/7#issuecomment-868996434_

It's still a bug in check-jsonschema, even if we now know a better workaround.

**Comment by foolioo** [comment]
@sirosen: i confirm the new release works file. there is no need for `require_serial: true`
